### PR TITLE
Embracing Poetry: includes version + deps bump

### LINKED ISSUE #818: Errors when installing new dependencies
## Overview
Adding a new dependency into requirements.txt causes errors to occur in the github actions workflow.

For example, 
When I added the `rich` dependency to the requirements.txt file I got this output for the test:
https://github.com/facebookresearch/Mephisto/runs/7237323897?check_suite_focus=true

The issue is not exclusive to `rich` as I also got this error when trying to add the `detoxify` dependency.

### PR DESCRIPTION
**Pull request by JackUrb**
# Overview 
Preparing for the release of `1.0.2`, this PR moves us to fully adopt `poetry` as our python package manager. This is handled by moving all of the details that used to be in `setup.py`, `requirements.txt`, and `MANIFEST.in` into the `pyproject.toml` file. We're adapting this as we needed editable installations with `pip install -e .` as described in https://github.com/python-poetry/poetry/issues/34, and following https://github.com/python-poetry/poetry-core/pull/182 we could actually have it. A year late, but eventually is better than never!

After this it should be easier to modify and manage packages, and to deal with ParlAI dependencies (perhaps we can push them to adopt as well?). 

Should resolve #818 and #768.

Note - some of the `pyproject.toml` file is still commented out. This is because there's some nicer syntax coming out in poetry 1.2 that I'd like to adopt, but I can't get tests to work using it _just_ yet so I've left it commented out.

### CODE REVIEW

**Comment by pringshia** [comment]
Seems like there are a bunch of test failures - possible that the dependencies in pyproject.toml aren't up to date?

**Comment by pringshia** [comment]
Will this mean `pip install -e` won't work anymore btw? In that case we should update our Github Actions tests and Dockerfiles to use `poetry install` instead of `pip install -e`. 

https://github.com/facebookresearch/Mephisto/search?q=pip+install

**Comment by JackUrb** [comment]
Debugging the tests, but `pip install -e .` still works perfectly :)

**Comment by JackUrb** [comment]
Alright solved the issue by commenting out the fancy poetry 1.2 syntax, will return to that when the release is finally cut.

**Pull request merged**
