### PR TITLE
Update `@blueprintjs/core` version

### LINKED ISSUE #827: Upgrade @blueprintjs/core version to allow for React 18 compatibility
The [`cra-template-mephisto-review`](https://github.com/facebookresearch/Mephisto/tree/main/packages/cra-template-mephisto-review) package uses  `@blueprintjs/core@3.38.1` which is not compatible with React 18. In order to support React 18, we'll need to update to `@blueprintjs/core@4.1.0` or higher.

Once upgraded, the [starter tutorial](https://mephisto.ai/docs/guides/tutorials/review-cli/#1-use-the-starter-template) should still continue to work.

### PR DESCRIPTION
**Pull request by pringshia**
Fixes #827

Upgrades the `@blueprintjs/core` dependency for `cra-template-mephisto-review`

**Update**: Includes a capitalization file import fix as well

## Testing

Built a new review app using the updated template. The following was run from the Mephisto root directory:

```
npx clear-npx-cache # had to do this first in my case: https://stackoverflow.com/a/70358238
npx create-react-app --template file:packages/cra-template-mephisto-review template-test
cd template-test
npm start
```

### CODE REVIEW

**Comment by Etesam913** [comment]
I ran it in my root Mephisto directory and got this:
Screen Shot 2022-08-01 at 1 14 30 PM

Screen Shot 2022-08-01 at 1 14 37 PM

**Comment by pringshia** [comment]
> In what directory did you run this in?
> 
> You might want to add it to the testing section of your pr as well

Good call out. Updated. It was from the Mephisto root directory

**Comment by pringshia** [comment]
> npx create-react-app --template file:packages/cra-template-mephisto-review template-test
> cd template-test
> npm start

**Comment by pringshia** [comment]
> I ran it in my root Mephisto directory and got this:

Hmm, I'm unable to reproduce this. Tried again and seems to works on my end 🤔

**Comment by Etesam913** [comment]
In CollectionView.jsx this folder name should be capitalized in the path. Weird, I feel like that should create an error for you as well ...
Screen Shot 2022-08-01 at 1 21 57 PM

**Comment by Etesam913** [comment]
Is is supposed to have this red banner at the bottom?
Screenshot 2022-08-01 at 13-24-09 Mephisto Review

**Comment by pringshia** [comment]
> In `CollectionView.jsx` this folder name should be capitalized in the path. Weird, I feel like that should create an error for you as well ...

Why would it need to be capitalized? If it's lowercase in both the source code as well as the file system, shouldn't it just work?

The red banner is expected, but not ideal. It could probably be a little bit more informational rather than the generic error handling we have in place here. The reason is that the interface is meant to be loaded with data through the `mephisto review` command. When you just do `npm start` you don't invoke it with any data piped in.

**Comment by Etesam913** [comment]
Mine is capitalized. I deleted the template-test and installed it again and it the Pagination folder is still capitalized. 
Screen Shot 2022-08-01 at 1 30 48 PM

**Comment by Etesam913** [comment]
The folder seems to be capitalized on the `main` branch: https://github.com/facebookresearch/Mephisto/tree/main/packages/cra-template-mephisto-review/template/src/components

**Comment by pringshia** [comment]
Yep, since the folder is capitalized on Github that should be the source of truth. I'm not sure why my local Mephisto repo didn't have it as such and was out of sync (git diff also doesn't seem to notify for these cases). I've updated the import to reflect the capitalized folder name.

**Pull request merged**
