### PR TITLE
Fixing cli bugs with mephisto web and mephisto review

### PR DESCRIPTION
**Pull request by Etesam913**
## Overview
Currently running `mephisto review` and `mephisto web` will give you the following
```bash
Traceback (most recent call last):
  File "/Users/etesam1/Documents/Mephisto/venv/bin/mephisto", line 8, in <module>
    sys.exit(cli())
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/etesam1/Documents/Mephisto/mephisto/client/cli.py", line 104, in review
    from mephisto.client.review.review_server import run
  File "/Users/etesam1/Documents/Mephisto/mephisto/client/review/review_server.py", line 7, in <module>
    from flask import Flask, Blueprint, send_file, jsonify, request  # type: ignore
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/markupsafe/__init__.py)
```

After searching online, this can be fixed by setting markupsafe = "2.0.1", which I did in the `pyproject.toml`

However, running then `mephisto web` gives this error: 

```bash
Traceback (most recent call last):
  File "/Users/etesam1/Documents/Mephisto/venv/bin/mephisto", line 8, in <module>
    sys.exit(cli())
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/rich_click/rich_group.py", line 21, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/etesam1/Documents/Mephisto/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/etesam1/Documents/Mephisto/mephisto/client/cli.py", line 37, in web
    from mephisto.client.full.server import app
ImportError: cannot import name 'app' from 'mephisto.client.full.server' (/Users/etesam1/Documents/Mephisto/mephisto/client/full/server.py)
```

I'm not exactly sure about this error

### CODE REVIEW

**Comment by JackUrb** [comment]
Ah at some point it seems we moved that server into a `main` function. Perhaps instead we should rename the `main` in there to `get_app` and have it return the app?

**Comment by Etesam913** [comment]
I made it into a function named, get_app(). This launches the server:
Screen Shot 2022-07-19 at 4 35 14 PM

However, when I visit the link I get a blank page with the following error in the console:
Screen Shot 2022-07-19 at 4 42 57 PM

**Comment by Etesam913** [comment]
Going to the file shows a type error, not exactly sure how to fix it

**Comment by Etesam913** [comment]
Is this a command that is still in use? The code seems very old...

**Comment by pringshia** [comment]
This code is indeed very old and hasn't been maintained for several years

**Comment by JackUrb** [comment]
It's been an item in the long-term vision for the project, but a solid dashboard that's also able to handle very custom workflows is a hard goal

**Comment by Etesam913** [comment]
Can I merge this in now because this fixes some formatting bugs and the bug with `mephisto review`? The bug with `mephisto web` will probably take a longer time to fix and can be done in a separate pr.

**Pull request merged**
