### PR TITLE
EC2Architect fixed warning when domain is in use

### PR DESCRIPTION
**Pull request by Yash621**
This PR is in respect to issue #614 and continuation of PR #617
@JackUrb please review it , I have done all the changes that you suggested .

### CODE REVIEW

**Review by JackUrb — COMMENTED** [review]
You're still making a lot of unrelated formatting changes in `ec2_helpers.py` - I don't think these are related to the given PR.

**Comment by Yash621** [comment]
@JackUrb  actually i am not ,I am still figuring out why that file is being formatted ,can you please suggest how to fix this formatting issue ,I have ran black also on both the ec2_helpers.py and ec2_architect.py file but still getting formatting issue on the PR.

**Comment by JackUrb** [comment]
Well, for `ec2_helpers.py` at least you can just discard your changes on the file, as all of the changes there are formatting. When you run `black`, what is the output in your console? Perhaps you're not committing the black output changes.

**Comment by Yash621** [comment]
@JackUrb when i run black it shows 
All done! 
1 file left unchanged.
due to which i am not understanding that why even after formatting with black why it is not accepting code style ?

**Comment by JackUrb** [comment]
> @JackUrb when i run black it shows All done! 1 file left unchanged. due to which i am not understanding that why even after formatting with black why it is not accepting code style ?

What is the full command you are running? Ideally you should pip install `pre-commit` so that black automatically runs on files in your checkout when you commit.

**Comment by Yash621** [comment]
@JackUrb for some reason pre-commit is not working ,so i have to run black individual files every time i edit them

**Comment by Yash621** [comment]
@JackUrb I have fixed the formatting issues ,now their are no conflicts ,are there any additional changes that i need to do ?

**Review by JackUrb — APPROVED** [review]
Thanks for going through the manual effort here @Yash621. I'd really like to help figure out why the automated tooling isn't working for you.

At the very least, running `pre-commit run --all-files` should have been able to automatically run on your commit and made the changes, perhaps that's something to try next time?

In any case, thanks again for the contribution and for sticking this one out!

**Comment by Yash621** [comment]
@JackUrb sorry to bother you, but I just wanted to ask a favor that is if you could write a recommendation for me on linkedin,
I would be really grateful 😊

Here is my linkedin Id: 

https://www.linkedin.com/in/yash-goel-610543213

I have sent you a connection request already 😊

**Pull request merged**
