### PR TITLE
Update documentation to reflect that make_qualification_dict takes 3 arguments.

### PR DESCRIPTION
**Pull request by xksteven**
make_qualification_dict takes in 3 arguments and these examples in the documentation pass in only two.
Running it with only two gives the following error:

```bash
line 401, in main
    make_qualification_dict(
TypeError: make_qualification_dict() missing 1 required positional argument: 'value'
```

I thought it easier to update the documentation then the code to make the 3rd argument default to None.

### CODE REVIEW

**Comment by JackUrb** [comment]
Thanks for noting and resolving this @xksteven!

@pringshia any idea why the doc deploy test step appears to be failing here?

**Comment by pringshia** [comment]
@JackUrb updating yarn should fix it, you can run:

```
yarn set version latest
```

I have this done in a separate WIP branch but it's part of many other changes that are nowhere near ready to be merged

**Comment by xksteven** [comment]
Let me know if there's anything else I should do for the PR.

**Comment by pringshia** [comment]
Hey @xksteven thanks for your contribution. I just merged in #920 which should fix the broken test in this PR. Could you please pull down the latest `main` into your repo, and rebase this PR?

**Comment by xksteven** [comment]
@pringshia All the checks successfully pass now.

**Review by pringshia — APPROVED** [review]

**Pull request merged**
