### PR TITLE
heroku architect: fix default git branch name

### LINKED ISSUE #823: Heroku deployment fails if the default git branch is not "master"
As we know, the default branch on git is being changed from `master` to `main` at various places (e.g. Github)

Heroku deployment has `git init` without a branch name 
https://github.com/facebookresearch/Mephisto/blob/588d5ca3eece7fd9edc394a5d42813b5cdd3dd83/mephisto/abstractions/architects/heroku_architect.py#L352

Which results in default/initial branch name resolved as per user's setting (in my case `main` not `master`) 
whereas `git push` has hardcoded `master`  branch

https://github.com/facebookresearch/Mephisto/blob/588d5ca3eece7fd9edc394a5d42813b5cdd3dd83/mephisto/abstractions/architects/heroku_architect.py#L422

So I get this error: 

```
  File "/Users/tg/work/projects/darma/Mephisto/mephisto/operations/operator.py", line 286, in launch_task_run_or_die
    task_url = live_run.architect.deploy()
  File "/Users/tg/work/projects/darma/Mephisto/mephisto/abstractions/architects/heroku_architect.py", line 492, in deploy
    return self.__setup_heroku_server()
  File "/Users/tg/work/projects/darma/Mephisto/mephisto/abstractions/architects/heroku_architect.py", line 422, in __setup_heroku_server
    sh.git(shlex.split(f"-C {heroku_server_directory_path} push -f heroku master"))
  File "/Users/tg/opt/miniconda3/envs/darma/lib/python3.9/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/Users/tg/opt/miniconda3/envs/darma/lib/python3.9/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/Users/tg/opt/miniconda3/envs/darma/lib/python3.9/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/Users/tg/opt/miniconda3/envs/darma/lib/python3.9/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/bin/git -C /Users/tg/work/projects/data/runs/NO_PROJECT/26/build/heroku_server_xxx_26/router push -f heroku master

  STDOUT:

  STDERR:
error: src refspec master does not match any
error: failed to push some refs to 'https://git.heroku.com/blahblah.git'
```

### PR DESCRIPTION
**Pull request by thammegowda**
Closes #823

### CODE REVIEW

**Comment by JackUrb** [comment]
Hi @thammegowda, thanks for identifying and resolving this issue! Rather than forcing the `master` name though, could we force `main` and then also update the architect to reflect this decision?

**Comment by thammegowda** [comment]
welcome! 
I thought of forcing `main` but I was not so sure if heroku supports deployment from `main`. [I just found that it does!](https://devcenter.heroku.com/changelog-items/1829#:~:text=Heroku%20now%20supports%20main%20as%20the%20primary%20deployment,workflows%20that%20depend%20on%20master%20are%20not%20affected.)

So yes, we can force `main` instead of `master`. I will update the PR

**Review by JackUrb — APPROVED** [review]
Thanks for finding and fixing this issue!

**Comment by JackUrb** [comment]
Ah also could you resolve the `black` issues? I'll merge this in right after!

**Comment by thammegowda** [comment]
@JackUrb I tried fixing the issue. Please run the checks and let me know if it had fixed. 
I havent used `black` before and if my recent commit hasn't fixed it, then give me a little bit more info about what the error is. Thanks!

**Comment by JackUrb** [comment]
Generally we manage running `black` through [pre-commit](https://github.com/facebookresearch/Mephisto/blob/main/CONTRIBUTING.md#core-contributions). It's easy setup in case you choose to contribute in the future!

**Pull request merged**
